const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Config plugin for the embedded Tor module.
 *
 * The interesting work here is not wiring the module up — autolinking does
 * that. It is stopping the platform from quietly exfiltrating Tor's state.
 */

const BACKUP_RULES_FILE = "khabardar_tor_backup_rules.xml";

/**
 * Keep Arti's state out of Android auto-backup.
 *
 * Android backs an app's private files up to the user's Google Drive by
 * default. For most apps that is a feature. Here it would upload Tor's
 * persistent state — including the **guard set**, the small number of entry
 * relays this device deliberately reuses — to a third party, where it is
 * subject to legal process and links every restore of that backup to the same
 * user. Guards exist to resist traffic analysis; a copy of them in cloud
 * storage undoes that.
 *
 * Excluding rather than disabling backup entirely: the rest of the app's data
 * is already encrypted at rest and users should keep their backups.
 */
function withTorBackupExclusion(config) {
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const resDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml"
      );
      fs.mkdirSync(resDir, { recursive: true });

      // These rules REPLACE expo-secure-store's, because Android allows one
      // `fullBackupContent` per application and whichever plugin runs last
      // wins. expo-secure-store notices the clash and warns, then leaves its
      // own rules unapplied — so anything it would have excluded has to be
      // repeated here or it silently becomes backed up.
      //
      // That is exactly what happened the first time this plugin shipped:
      // `sharedpref/SecureStore` went from excluded to included, which is where
      // the identity key, the recovery phrase, the at-rest encryption keys, the
      // stealth PINs and the Semaphore secret all live. Those values are
      // encrypted under a non-exportable Keystore key, so the backup carried
      // ciphertext rather than usable secrets — but a restored device then
      // holds entries it can never decrypt, and silently overriding another
      // library's security control is not something to do by accident.
      //
      // Keep this list in sync with expo-secure-store's
      // `secure_store_backup_rules.xml` if that package is upgraded.
      const rules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor.
     Covers BOTH this module's exclusions and expo-secure-store's, because
     Android permits only one fullBackupContent per application. -->
<full-backup-content>
    <include domain="sharedpref" path="." />
    <!-- expo-secure-store: keystore-encrypted values. Restoring these to a new
         device yields entries that can never be decrypted. -->
    <exclude domain="sharedpref" path="SecureStore" />
    <!-- Arti's guard set and directory cache. A backed-up guard set is
         linkable across restores and subject to legal process. -->
    <exclude domain="file" path="tor/" />
    <exclude domain="database" path="tor/" />
    <exclude domain="sharedpref" path="khabardar.tor.xml" />
</full-backup-content>
`;
      fs.writeFileSync(path.join(resDir, BACKUP_RULES_FILE), rules, "utf8");

      // Android 12+ reads a separate data-extraction file for cloud backup and
      // device-to-device transfer. Both paths have to be closed, and both have
      // to carry expo-secure-store's exclusion for the same reason as above.
      const transferRules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor. Android 12+ equivalent of the full-backup rules,
     including expo-secure-store's exclusions. -->
<data-extraction-rules>
    <cloud-backup>
        <include domain="sharedpref" path="." />
        <exclude domain="sharedpref" path="SecureStore" />
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </cloud-backup>
    <device-transfer>
        <include domain="sharedpref" path="." />
        <exclude domain="sharedpref" path="SecureStore" />
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </device-transfer>
</data-extraction-rules>
`;
      fs.writeFileSync(
        path.join(resDir, "khabardar_tor_data_extraction_rules.xml"),
        transferRules,
        "utf8"
      );

      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_FILE.replace(".xml", "")}`;
    application.$["android:dataExtractionRules"] =
      "@xml/khabardar_tor_data_extraction_rules";
    return cfg;
  });
}

/**
 * iOS equivalent.
 *
 * The `isExcludedFromBackup` resource value set in ExpoTorModule.swift is the
 * real mechanism; this only documents the dependency in the Info.plist so it is
 * visible to anyone auditing the build rather than buried in Swift.
 */
function withTorInfoPlist(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.KhabardarTorEmbedded = true;
    return cfg;
  });
}

// minSdkVersion 24 and iOS 15.1 are declared by android/build.gradle and the
// podspec respectively, so there is nothing for the plugin to do about them.

const withExpoTor = (config) => {
  config = withTorBackupExclusion(config);
  config = withTorInfoPlist(config);
  return config;
};

module.exports = createRunOncePlugin(withExpoTor, "expo-tor", "0.1.0");
