const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Config plugin for the embedded Tor module.
 *
 * The interesting work here is not wiring the module up — autolinking does
 * that. It is stopping the platform from quietly exfiltrating Tor's state.
 */

const BACKUP_RULES_FILE = "khabardar_tor_backup_rules.xml";

/**
 * Keep Arti's state out of Android auto-backup.
 *
 * Android backs an app's private files up to the user's Google Drive by
 * default. For most apps that is a feature. Here it would upload Tor's
 * persistent state — including the **guard set**, the small number of entry
 * relays this device deliberately reuses — to a third party, where it is
 * subject to legal process and links every restore of that backup to the same
 * user. Guards exist to resist traffic analysis; a copy of them in cloud
 * storage undoes that.
 *
 * Excluding rather than disabling backup entirely: the rest of the app's data
 * is already encrypted at rest and users should keep their backups.
 */
function withTorBackupExclusion(config) {
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const resDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml"
      );
      fs.mkdirSync(resDir, { recursive: true });

      // `files/tor` is Arti's state dir and `cache/tor` its cache — see the
      // paths chosen in ExpoTorModule.kt.
      const rules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor. Keeps Tor's guard set and directory cache out of
     Google Drive backups: a backed-up guard set is linkable across restores
     and subject to legal process. -->
<full-backup-content>
    <exclude domain="file" path="tor/" />
    <exclude domain="database" path="tor/" />
    <exclude domain="sharedpref" path="khabardar.tor.xml" />
</full-backup-content>
`;
      fs.writeFileSync(path.join(resDir, BACKUP_RULES_FILE), rules, "utf8");

      // Android 12+ reads a separate data-extraction file for cloud backup and
      // device-to-device transfer. Both paths have to be closed.
      const transferRules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor. Android 12+ equivalent of the full-backup rules. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </device-transfer>
</data-extraction-rules>
`;
      fs.writeFileSync(
        path.join(resDir, "khabardar_tor_data_extraction_rules.xml"),
        transferRules,
        "utf8"
      );

      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_FILE.replace(".xml", "")}`;
    application.$["android:dataExtractionRules"] =
      "@xml/khabardar_tor_data_extraction_rules";
    return cfg;
  });
}

/**
 * iOS equivalent.
 *
 * The `isExcludedFromBackup` resource value set in ExpoTorModule.swift is the
 * real mechanism; this only documents the dependency in the Info.plist so it is
 * visible to anyone auditing the build rather than buried in Swift.
 */
function withTorInfoPlist(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.KhabardarTorEmbedded = true;
    return cfg;
  });
}

// minSdkVersion 24 and iOS 15.1 are declared by android/build.gradle and the
// podspec respectively, so there is nothing for the plugin to do about them.

const withExpoTor = (config) => {
  config = withTorBackupExclusion(config);
  config = withTorInfoPlist(config);
  return config;
};

module.exports = createRunOncePlugin(withExpoTor, "expo-tor", "0.1.0");
