const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Config plugin for the embedded Tor module.
 *
 * The interesting work here is not wiring the module up — autolinking does
 * that. It is stopping the platform from quietly exfiltrating Tor's state.
 */

const BACKUP_RULES_FILE = "khabardar_tor_backup_rules.xml";

/**
 * Keep Arti's state out of Android auto-backup.
 *
 * Android backs an app's private files up to the user's Google Drive by
 * default. For most apps that is a feature. Here it would upload Tor's
 * persistent state — including the **guard set**, the small number of entry
 * relays this device deliberately reuses — to a third party, where it is
 * subject to legal process and links every restore of that backup to the same
 * user. Guards exist to resist traffic analysis; a copy of them in cloud
 * storage undoes that.
 *
 * Cloud backup is disabled outright by this plugin (`android:allowBackup=false`
 * on the application tag) — see the reasoning in app.json. Expo does not honour
 * `android.allowBackup` as a config key, so writing it only in app.json would
 * be a comment that a clean prebuild ignores. The full-backup rules below are
 * inert while backup is off; they are kept deliberately: they are the correct
 * rules if anyone ever turns backup back on, and a file that says nothing is
 * worse than one that says the right thing. The data-extraction rules are NOT
 * inert; `allowBackup` does not govern device-to-device transfer on Android
 * 12+, which is still permitted so users can migrate phones.
 */
function withTorBackupExclusion(config) {
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const resDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml"
      );
      fs.mkdirSync(resDir, { recursive: true });

      // These rules REPLACE expo-secure-store's, because Android allows one
      // `fullBackupContent` per application and whichever plugin runs last
      // wins. expo-secure-store notices the clash and warns, then leaves its
      // own rules unapplied — so anything it would have excluded has to be
      // repeated here or it silently becomes backed up.
      //
      // That is exactly what happened the first time this plugin shipped:
      // `sharedpref/SecureStore` went from excluded to included, which is where
      // the identity key, the recovery phrase, the at-rest encryption keys, the
      // stealth PINs and the Semaphore secret all live. Those values are
      // encrypted under a non-exportable Keystore key, so the backup carried
      // ciphertext rather than usable secrets — but a restored device then
      // holds entries it can never decrypt, and silently overriding another
      // library's security control is not something to do by accident.
      //
      // Keep this list in sync with expo-secure-store's
      // `secure_store_backup_rules.xml` if that package is upgraded.
      const rules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor.
     Covers BOTH this module's exclusions and expo-secure-store's, because
     Android permits only one fullBackupContent per application. -->
<full-backup-content>
    <include domain="sharedpref" path="." />
    <!-- expo-secure-store: keystore-encrypted values. Restoring these to a new
         device yields entries that can never be decrypted. -->
    <exclude domain="sharedpref" path="SecureStore" />
    <!-- Arti's guard set and directory cache. A backed-up guard set is
         linkable across restores and subject to legal process. -->
    <exclude domain="file" path="tor/" />
    <exclude domain="database" path="tor/" />
    <exclude domain="sharedpref" path="khabardar.tor.xml" />
</full-backup-content>
`;
      fs.writeFileSync(path.join(resDir, BACKUP_RULES_FILE), rules, "utf8");

      // Android 12+ reads a separate data-extraction file for cloud backup and
      // device-to-device transfer. Both paths have to be closed, and both have
      // to carry expo-secure-store's exclusion for the same reason as above.
      const transferRules = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by expo-tor. Android 12+ equivalent of the full-backup rules,
     including expo-secure-store's exclusions. -->
<data-extraction-rules>
    <!-- Cloud backup is already off at the manifest level (allowBackup=false);
         this block is belt and braces. It can afford to stay an allowlist. -->
    <cloud-backup>
        <include domain="sharedpref" path="." />
        <exclude domain="sharedpref" path="SecureStore" />
        <exclude domain="sharedpref" path="khabardar.tor.xml" />
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </cloud-backup>
    <!-- Device-to-device transfer is meant to keep working, so this block must
         carry no <include>. One <include> turns the whole block into an
         allowlist: "sharedpref only" would silently drop AsyncStorage — the
         reports, tips and follows — which lives in the database domain, and the
         transfer would arrive looking like a fresh install. Excludes alone mean
         "everything except", which is what app.json promises. -->
    <device-transfer>
        <exclude domain="sharedpref" path="SecureStore" />
        <exclude domain="sharedpref" path="khabardar.tor.xml" />
        <exclude domain="file" path="tor/" />
        <exclude domain="database" path="tor/" />
    </device-transfer>
</data-extraction-rules>
`;
      fs.writeFileSync(
        path.join(resDir, "khabardar_tor_data_extraction_rules.xml"),
        transferRules,
        "utf8"
      );

      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    // Expo has no first-class app.json key for this. If it is not written here,
    // a clean prebuild restores Android's default of true and Auto Backup
    // uploads the reporter's local state to their Google account.
    application.$["android:allowBackup"] = "false";
    application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_FILE.replace(".xml", "")}`;
    application.$["android:dataExtractionRules"] =
      "@xml/khabardar_tor_data_extraction_rules";
    return cfg;
  });
}

/**
 * iOS equivalent.
 *
 * The `isExcludedFromBackup` resource value set in ExpoTorModule.swift is the
 * real mechanism; this only documents the dependency in the Info.plist so it is
 * visible to anyone auditing the build rather than buried in Swift.
 */
function withTorInfoPlist(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.KhabardarTorEmbedded = true;
    return cfg;
  });
}

// minSdkVersion 24 and iOS 15.1 are declared by android/build.gradle and the
// podspec respectively, so there is nothing for the plugin to do about them.

/**
 * Alternate launcher entries so the home-screen icon can stop saying
 * Khabardar. The lock-screen disguise is worthless if the icon is the
 * evidence. These aliases start disabled; the native module enables one
 * when the user picks a disguise.
 *
 * This is a weak control and the UI says so: Settings, package name and
 * a forensic listing of installed apps still name the real app.
 */
function withStealthLauncher(config) {
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const drawable = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "drawable"
      );
      fs.mkdirSync(drawable, { recursive: true });
      fs.writeFileSync(
        path.join(drawable, "ic_disguise_calculator.xml"),
        CALCULATOR_ICON,
        "utf8"
      );
      fs.writeFileSync(path.join(drawable, "ic_disguise_notes.xml"), NOTES_ICON, "utf8");
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    const aliases = application["activity-alias"] || [];
    for (const spec of STEALTH_ALIASES) {
      if (aliases.some((a) => a.$["android:name"] === spec.name)) continue;
      aliases.push({
        $: {
          "android:name": spec.name,
          "android:enabled": "false",
          "android:exported": "true",
          "android:icon": spec.icon,
          "android:roundIcon": spec.icon,
          "android:label": spec.label,
          "android:targetActivity": ".MainActivity",
        },
        "intent-filter": [
          {
            action: [{ $: { "android:name": "android.intent.action.MAIN" } }],
            category: [{ $: { "android:name": "android.intent.category.LAUNCHER" } }],
          },
        ],
      });
    }
    application["activity-alias"] = aliases;
    return cfg;
  });
}

const STEALTH_ALIASES = [
  {
    name: ".MainActivityCalculator",
    label: "Calculator",
    icon: "@drawable/ic_disguise_calculator",
  },
  {
    name: ".MainActivityNotes",
    label: "Notes",
    icon: "@drawable/ic_disguise_notes",
  },
];

const CALCULATOR_ICON = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#2B2B2B" android:pathData="M18,18h72v72h-72z"/>
    <path android:fillColor="#E8E8E8" android:pathData="M26,26h56v16h-56z"/>
    <path android:fillColor="#5A5A5A" android:pathData="M26,50h14v10h-14zM47,50h14v10h-14zM68,50h14v10h-14zM26,66h14v10h-14zM47,66h14v10h-14zM68,66h14v10h-14zM26,82h14v8h-14zM47,82h14v8h-14zM68,82h14v8h-14z"/>
</vector>
`;

const NOTES_ICON = `<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#F4E7C3" android:pathData="M24,16h60v76h-60z"/>
    <path android:fillColor="#C9B48A" android:pathData="M24,16h60v8h-60z"/>
    <path android:fillColor="#8A7A55" android:pathData="M34,40h40v3h-40zM34,52h40v3h-40zM34,64h40v3h-40zM34,76h28v3h-28z"/>
</vector>
`;

const withExpoTor = (config) => {
  config = withTorBackupExclusion(config);
  config = withStealthLauncher(config);
  config = withTorInfoPlist(config);
  return config;
};

module.exports = createRunOncePlugin(withExpoTor, "expo-tor", "0.1.0");
